Name: Product
Host: 127.0.0.1
Port: 8001

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

Mysql:
  DataSource: root:root@tcp(mysql:3306)/go-zero?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: localhost:6379
    Type: node # node可以不写，可以设为cluster


ProductRpc:
  Etcd:
    Hosts:
      - localhost:2379
    Key: product.rpc